name: Publish

on:
  push:
    # only publish on version tags
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./android

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        path: ./android
        submodules: recursive

    - name: set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'

    - name: Download aar
      run: ./downloadAar.sh

    - name: Check aar exists
      run: test -f "libwebrtc.aar"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Publish to artifactory
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: ./gradlew publish
